
function(yakl_set_cxx_flags YAKL_CXX_SOURCE)

  if ("${YAKL_ARCH}" STREQUAL "CUDA")
    set_source_files_properties(${YAKL_CXX_SOURCE} PROPERTIES LANGUAGE CUDA)
    set(YAKL_CXX_FLAGS "-D__USE_CUDA__ --expt-extended-lambda --expt-relaxed-constexpr ${CUDA_FLAGS}")
    set_source_files_properties(${YAKL_CXX_SOURCE} PROPERTIES COMPILE_FLAGS "${YAKL_CXX_FLAGS}")
    include_directories(cub)
  elseif ("${YAKL_ARCH}" STREQUAL "HIP")
    set(YAKL_CXX_FLAGS "-D__USE_HIP__ ${HIP_FLAGS}")
    set_source_files_properties(${YAKL_CXX_SOURCE} PROPERTIES COMPILE_FLAGS "${YAKL_CXX_FLAGS}")
    include_directories(hipCUB/hipcub/include)
    include_directories(rocPRIM/rocprim/include)
  elseif ("${YAKL_ARCH}" STREQUAL "SYCL")
    set(YAKL_CXX_FLAGS "-D__USE_SYCL__ --intel -fsycl ${SYCL_FLAGS}")
    set_source_files_properties(${YAKL_CXX_SOURCE} PROPERTIES COMPILE_FLAGS "${YAKL_CXX_FLAGS}")
  elseif ("${YAKL_ARCH}" STREQUAL "OPENMP45")
    set(YAKL_CXX_FLAGS "-D__USE_OPENMP45__ ${OPENMP45_FLAGS}")
    set_source_files_properties(${YAKL_CXX_SOURCE} PROPERTIES COMPILE_FLAGS "${YAKL_CXX_FLAGS}")
  else()
  endif()

endfunction()
